let strastgyList=[
    {   
        id:1,
        Name:"黑神话：悟空",
        English:"Black Myth: Wukong",
        coverUrl:"../img/Wukong.webp",
        carousel1:"../img/Wukong/1.jpg",
        carousel2:"../img/Wukong/2.jpg",
        carousel3:"../img/Wukong/3.jpg",
        money:"￥268",
        score:"9.8",
        classify:"动作|冒险|神话",
        strastgy:"1034",
        introduce:"《黑神话：悟空》是由游戏科学公司制作的以中国神话为背景的动作角色扮演游戏，将于2024年8月20日发售，简体中文PC标准版售价268人民币,数字豪华版售价328人民币。游戏中，玩家将扮演一位“天命人”，为了探寻昔日传说的真相，踏上一条充满危险与惊奇的西游之路。",
    },
    {
        id:2,
        Name:"无人深空",
        English:"No Man's Sky",
        coverUrl:"../img/NoManSky.webp",
        carousel1:"../img/NoManSky/1.jpg",
        carousel2:"../img/NoManSky/2.jpg",
        carousel3:"../img/NoManSky/3.jpg",
        money:"￥70",
        score:"9.1",
        classify:"开放世界|冒险|太空",
        strastgy:"1273",
        introduce:"《无人深空》是由Hello Games开发的一款太空冒险生存主题游戏。游戏于2016年8月9日正式登陆PS平台，于2016年8月12日登陆PC平台，在2018年7月24日登陆XboxOne平台，在2022年10月7日登陆Switch平台。在游戏中玩家可以扮演一名身处宇宙边缘的一个宇航员，自由探索这个陌生而具备吸引力的宇宙，最后回归宇宙中心",
    },
    {
        id:3,
        Name:"艾尔登法环",
        English:"Elden Ring",
        coverUrl:"../img/EndingRing.jpg",
        carousel1:"../img/EndingRing/1.jpg",
        carousel2:"../img/EndingRing/2.jpg",
        carousel3:"../img/EndingRing/3.jpg",
        money:"￥298",
        score:"9.6",
        classify:"动作|开放世界|类魂系列",
        strastgy:"2452",
        introduce:"《艾尔登法环》是From Software开发，万代南梦宫发行的黑暗幻想风开放世界角色扮演动作游戏。于2022年2月25日于Steam、PlayStation 4、PlayStation 5、Xbox One、Xbox Series X/Xbox Series S上发售。该游戏让玩家走进辽阔的场景与地下迷宫探索未知，挑战困难重重的险境，同时体验登场角色之间的利害关系谱成的群像剧。",
    },
    {
        id:4,
        Name:"幻兽帕鲁",
        English:"Palworld",
        coverUrl:"../img/Palworld.webp",
        carousel1:"../img/Palworld/1.jpg",
        carousel2:"../img/Palworld/2.jpg",
        carousel3:"../img/Palworld/3.jpg",
        money:"￥81",
        sale:"25",
        score:"9.3",
        classify:"动作|冒险|开放世界",
        strastgy:"2254",
        introduce:"《幻兽帕鲁》是Pocketpair开发的一款开放世界生存制作游戏，游戏于2023年11月2日至11月5日进行了封闭网络测试，于2024年1月18日发行抢先体验版本。游戏中，玩家可以在广阔的世界中收集神奇的生物“帕鲁”，派他们进行战斗、建造、做农活，工业生产等。",
    },
    {
        id:5,
        Name:"街头霸王6",
        English:"Street Fighter 6",
        coverUrl:"../img/StreetFighter6.webp",
        carousel1:"../img/StreetFighter6/1.jpg",
        carousel2:"../img/StreetFighter6/2.jpg",
        carousel3:"../img/StreetFighter6/3.jpg",
        money:"￥149",
        sale:"50",
        score:"9.5",
        classify:"2D格斗|格斗|街机",
        strastgy:"3365",
        introduce:"《街头霸王6》（Street Fighter 6）是由卡普空开发的一款格斗游戏作品，于 2023 年6月2日在 PlayStation 5、PlayStation 4、Xbox Series X|S 和Steam平台上线。游戏中通过简单操作即可使用，强化了攻击与防御的系统。在有效时机发动技能会出现华丽的演出，让玩家充分体验游戏的爽快感，使对战的情绪更为高涨。",
    },
    {
        id:6,
        Name:"怪物猎人：世界",
        English:"Monster Hunter：World",
        coverUrl:"../img/MonsterHunterWorld.jpg",
        carousel1:"../img/MonsterHunterWorld/1.jpg",
        carousel2:"../img/MonsterHunterWorld/2.jpg",
        carousel3:"../img/MonsterHunterWorld/3.jpg",
        money:"￥49",
        sale:"67",
        score:"9.5",
        classify:"动作|合作|角色扮演",
        strastgy:"2275",
        introduce:"《怪物猎人：世界》是卡普空采用MT Framework引擎开发制作的第三人称角色扮演类动作游戏，于2018年1月26日在PS4、Xbox One平台发售，2018年8月10日登陆PC端Steam平台，为《怪物猎人》系列作品之一。在游戏中，玩家将化身成猎人， 接受任务狩猎生活栖息在各种环境中的魔物。利用狩猎魔物取得的材料，制作更强的武器和防具， 挑战更强大的魔物。",
    },
    {
        id:7,
        Name:"空洞骑士：丝之歌",
        English:"Hollow Knight: Silksong",
        coverUrl:"../img/HollowKnight.webp",
        carousel1:"../img/HollowKnight/1.jpg",
        carousel2:"../img/HollowKnight/2.jpg",
        carousel3:"../img/HollowKnight/3.jpg",
        money:"￥",
        score:"9.8",
        classify:"动作|冒险|独立",
        strastgy:"614",
        introduce:"《空洞骑士：丝之歌（Hollow Knight Silksong）》是2017年《空洞骑士》的续作，拥有新剧情和关卡，还有新技能和敌人。登陆PC和Nintendo Switch平台。2021年2月1日据外媒Nintendo Everything报道，《空洞骑士》开发团队Team Cherry接受采访时谈到了《空洞骑士：丝绸之歌》完成之后计划，据开发者称，他们还有一款非《空洞骑士》类型的游戏在等待制作",
    },
    {
        id:8,
        Name:"冰汽时代 2",
        English:"Frostpunk2",
        coverUrl:"../img/Forstpuck2.jpg",
        carousel1:"../img/Forstpuck2/1.jpg",
        carousel2:"../img/Forstpuck2/2.jpg",
        carousel3:"../img/Forstpuck2/3.jpg",
        money:"￥149",
        score:"9.8",
        classify:"模拟|经营|生存",
        strastgy:"412",
        introduce:"《冰汽时代2》是由11 bit studios公司发行的一款末日城市建造生存游戏，预计将于2024年发行。续作设定在了毁灭性暴风雪平息后的30年，永无止尽的冰天雪地依旧覆盖着这片大地",
    },
    {
        id:9,
        Name:"怪物猎人：荒野",
        English:"Monster Hunter Wilds",
        coverUrl:"../img/monsterhunter.jpg",
        carousel1:"../img/monsterhunter/1.jpg",
        carousel2:"../img/monsterhunter/2.jpg",
        carousel3:"../img/monsterhunter/3.jpg",
        money:"￥",
        score:"9.8",
        classify:"动作|冒险|狩猎",
        strastgy:"924",
        introduce:"《怪物猎人：荒野》是CAPCOM制作发行的一款角色扮演类动作游戏，预计将于2025年在PlayStation 5、Xbox SeriesX|S、Steam发行。",
    },
    {
        id:10,
        Name:"潜行者2：切尔诺贝利之心",
        English:"S.T.A.L.K.E.R.2:Heart of Chernobyl",
        coverUrl:"../img/STALKER2.jpg",
        carousel1:"../img/STALKER2/1.jpg",
        carousel2:"../img/STALKER2/2.jpg",
        carousel3:"../img/STALKER2/3.jpg",
        money:"￥268",
        score:"82",
        classify:"动作|冒险|第一人称射击",
        strastgy:"1382",
        introduce:"《潜行者2：切尔诺贝利之心》（S.T.A.L.K.E.R. 2:Heart of Chernobyl）是由GSC Game World开发的第一人称射击游戏作品。",
    },
    {
        id:11,
        Name:"小小梦魇3",
        English:"Little Nightmares 3",
        coverUrl:"../img/LittleNightmares3.webp",
        carousel1:"../img/LittleNightmares3/1.jpg",
        carousel2:"../img/LittleNightmares3/2.jpg",
        carousel3:"../img/LittleNightmares3/3.jpg",
        money:"￥",
        score:"9.8",
        classify:"恐怖|冒险|解迷",
        strastgy:"236",
        introduce:"《小小梦魇3》是一款恐怖冒险游戏。是序小小梦魇1，小小梦魇2的续作，万代南梦宫欧洲于领英发布全新招聘信息暗示计划开发这一知名游戏 IP 续作，2023年5月已经开始招募专门从事《小小梦魇》IP 的工作人员。",
    },
    {
        id:12,
        Name:"荒野大镖客：救赎2",
        English:"Red Dead Redemption 2",
        coverUrl:"../img/RedDead2.webp",
        carousel1:"../img/RedDead2/1.jpg",
        carousel2:"../img/RedDead2/2.jpg",
        carousel3:"../img/RedDead2/3.jpg",
        money:"￥92",
        sale:"67",
        score:"9.7",
        classify:"动作|冒险|开放世界",
        strastgy:"2478",
        introduce:"《Red Dead Redemption 2》，简称RDR2，是Rockstar San Diego工作室制作，Rockstar Games公司发行的一款动作冒险类开放世界游戏，为2010年该公司发行的《Red Dead Redemption》的正统续作。游戏中述说亚瑟·摩根和声名狼藉的范德林德帮派的传奇故事，让玩家体验在19世纪的最后岁月里横跨美国的亡命之旅。",
    },
    {
        id:13,
        Name:"冰汽时代",
        English:"Frostpunk",
        coverUrl:"../img/Forstpunk.jpg",
        carousel1:"../img/ForstPunk1/1.jpg",
        carousel2:"../img/ForstPunk1/2.jpg",
        carousel3:"../img/ForstPunk1/3.jpg",
        money:"￥108",
        score:"9.3",
        classify:"模拟|经营|生存",
        strastgy:"782",
        introduce:"《冰汽时代》是11 bit studios制作的一款模拟策略游戏，于2018年4月24日发行。在游戏中，玩家将作为世上最后一座城市的管理者对人民及里面的基础设施进行管理。随着环境与资源的不断恶化，采取不同的决定及策略来确保城市的生存。",
    },
    {
        id:14,
        Name:"只狼：影度二逝",
        English:"SEKIRO: Shadows Die Twice",
        coverUrl:"../img/seikro.jpg",
        carousel1:"../img/seikro/1.jpg",
        carousel2:"../img/seikro/2.jpg",
        carousel3:"../img/seikro/3.jpg",
        money:"￥129",
        sale:"50",
        score:"9.8",
        classify:"动作|冒险|类魂系列",
        strastgy:"2622",
        introduce:"《只狼：影逝二度》（Sekiro：Shadows Die Twice）是一款由From Software制作的第三人称视角的动作冒险RPG类游戏，玩家将操控一位忍者，拯救他的主人——拥有日本贵族血统的大能的御子，并向他的天敌复仇。该游戏已于2019年3月22日全球同步上市，并支持中文版",
    },
    {
        id:15,
        Name:"生化危机4 重制版",
        English:"Resident Evil 4 Remake",
        coverUrl:"../img/ResidentEvil.png",
        carousel1:"../img/ResidentEvil/1.jpg",
        carousel2:"../img/ResidentEvil/2.jpg",
        carousel3:"../img/ResidentEvil/3.jpg",
        money:"￥149",
        sale:"25",
        score:"9.9",
        classify:"动作|冒险|恐怖",
        strastgy:"1452",
        introduce:"《生化危机4：重制版》是一款由卡普空（CAPCOM）制作的射击类恐怖游戏。游戏于2023年3月24日正式发售。登陆PlayStation 5，PlayStation 4，Xbox Series X，Xbox Series S，PC平台。 [2]2023年12月20日，《生化危机4：重制版》iPhone、iPad、Mac版本上线。游戏中玩家跟随里昂的视角，展开一场营救被绑架的总统千金之旅。",
    },
    
]

let strastgyBox = document.querySelector(".strastgy-box");
let strastgyStr = "";
strastgyList.forEach((item,index)=>{
    strastgyStr += `
           
                    <div class="movie-item">
                        <img src="${item.coverUrl}">
                        <p>${item.Name}</p>
                        <div>
                            <span class="score">${item.strastgy}篇攻略</span>
                        </div>
                    </div>
             
    `
})
strastgyBox.innerHTML = strastgyStr;